PROGRAM AREA;
VAR
    HEIGHT: REAL;
    WIDTH: REAL;
    PI: REAL;
    RAREA: REAL;
    SAREA: REAL;
    AREA: REAL;
BEGIN
PI := 3.14159;
READ (HEIGHT);
READ (WIDTH);
RAREA := HEIGHT * WIDTH;
SAREA := PI * WIDTH * WIDTH / 8.0;
AREA := RAREA - SAREA;
WRITE (' INPUT VALUES: ');
WRITE (HEIGHT);
WRITE (WIDTH);
WRITE (' AREA = ');
WRITE (AREA)
END